---
 - name: Enable Port Security
   hosts: sw1
   connection: network_cli
   gather_facts: no

   roles:
     - intfo

   tasks:

   - name: BACKUP CURRENT CONFIG
     ios_config:
       backup: yes
       backup_options:
         dir_path: "/etc/ansible/output/backups"
         filename: "{{inventory_hostname}}"

   - name: APPLY PORT SECURITY TEMPLATE
     ios_config:
       src: '../../templates/portSecurity.j2'
       save_when: never
       defaults: no


   - name: VERIFY PORT SECURITY
     ios_command:
       commands: show port-security
     register: pSecurity

   - name: POST CHANGE SAVE FOR SPEED
     ios_config:
       save_when: always
